# This is a basic workflow to help you get started with Actions

name: IMAGE BUILD

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    env:
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
            install: true

      - name: Creds for GCP
        run: |
          gcloud auth configure-docker -q

      - name: Build Images and Push to Registry
        run: |-
            docker build --platform=linux/amd64,linux/arm64 \
                         --output=type=registry,dest=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
                         -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .           
     
      - name: Set Latest
        run: |-
          gcloud container images add-tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA gcr.io/$PROJECT_ID/$SERVICE_NAME:latest
